NSUR/TazaKoom/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('news.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NSUR/news/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from .models import News

app_name = 'news'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.mainPage, name='mainPage'),
    url(r'^about/$', views.AboutUs.as_view(), name='aboutUs'),
    url(r'^rukovodstvo/$', views.Rukovodstvo.as_view(), name='rukovodstvo'),
    url(r'^news/', views.postListView, name='news'),
    url(r'^(?P<pk>\d+)/$', views.postDetailsView, name='details'),
    url(r'^emailus/$', views.emailUs, name='emailUs'),
    url(r'^search/$',views.search,name='search'),
    url(r'^email/',views.emailUsFooter,name='email')


]

NSUR/templates/sidebar/main.html
{% load static %}
<form method="GET" action="/search/">
<div class="input-group search-group">
    <input type="text" name="q" class="form-control btn-search" placeholder="Поиск" value="{{ request.get.q }}">
    <span class="input-group-btn">
        <button class="btn btn-default btn-search-icon" type="submit"></button>
    </span>
</div>
</form>
<div class="sidebar-left_menu">
    <div class="sidebar-left_menu_item">
        <h3 class="title-sidebar">Пресс-клипиинг</h3>
        <div class="news-list">
            <ul>
                {% for post in press %}
                    <li class="news-list_item"><a href="{% url 'news:details' pk=post.new.pk %}">{{ post.title|truncatechars:30 }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="sidebar-left_menu_item">
        <h3 class="title-sidebar">медиа бокс</h3>
        <div class="news-tab">
            <ul class="nav nav-tabs nav-news-tabs" role="tablist">
                <li role="presentation" class="active"><a href="#photo" aria-controls="photo"
                                                          role="tab" data-toggle="tab">Фото</a></li>
                <li role="presentation"><a href="#video" aria-controls="video" role="tab"
                                           data-toggle="tab">Видео</a></li>
            </ul>
            <div class="tab-content tab-news">
                <div role="tabpanel" class="tab-pane active" id="photo">
                    {% for photopost in photo %}
                        <div class="tab-news_item">
                            <a class="tab-news_item_link clearfix" href="{% url 'news:details' pk=photopost.photo.pk %}">
                                <img src="{{ photopost.photo.pic.url }}" width="101" height="81"
                                     alt="news image">
                                <div class="tab-news_item_detail">
                                    <span class="tab-news_item_detail_date">{{ photopost.photo.published|date }}</span>
                                    <h4 class="tab-news_item_detail_title">{{ photopost.title }}</h4>
                                </div>
                            </a>
                        </div>
                    {% endfor %}

                </div>
                <div role="tabpanel" class="tab-pane" id="video">
                    {% for videopost in video %}
                        <div class="tab-news_item clearfix">
                            <div class="news_card_img--wrap pull-left">
                                <img src="{{ videopost.video.pic.url }}" width="101" height="81"
                                     alt="news image">
                                <span class="play-icon play-icon--small">
                                    <span></span>
                                </span>
                            </div>
                            <a class="tab-news_item_link" href="{% url 'news:details' pk=videopost.video.pk %}">
                                <div class="tab-news_item_detail">
                                    <span class="tab-news_item_detail_date">{{ videopost.video.published|date }}</span>
                                    <h4 class="tab-news_item_detail_title">{{ videopost.title }}</h4>
                                </div>
                            </a>
                        </div>
                    {% endfor %}

                </div>
            </div>
        </div>
    </div>
    <div class="sidebar-left_menu_item">
        <h3 class="title-sidebar">общая информация о секретариате</h3>
        <div class="info-list">
            <ul>
                <li class="info-list_item"><a href="#">о нас</a></li>
                <li class="info-list_item"><a href="#">руководство</a></li>
                <li class="info-list_item"><a href="#">эксперты</a></li>
                <li class="info-list_item"><a href="#">национальный совет</a></li>
                <li class="info-list_item"><a href="#">нормативные документы</a></li>
                <li class="info-list_item"><a href="{% url 'news:emailUs' %}">обратная связь</a></li>
            </ul>
        </div>
    </div>
</div>