NSUR/TazaKoom/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('news.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NSUR/news/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from .models import News

app_name = 'news'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.mainPage, name='mainPage'),
    url(r'^about/$', views.AboutUs.as_view(), name='aboutUs'),
    url(r'^rukovodstvo/$', views.Rukovodstvo.as_view(), name='rukovodstvo'),
    url(r'^news/', views.postListView, name='news'),
    url(r'^(?P<pk>\d+)/$', views.postDetailsView, name='details'),
    url(r'^emailus/$', views.emailUs, name='emailUs'),
    url(r'^search/$',views.search,name='search'),
    url(r'^email/',views.emailUsFooter,name='email')


]

NSUR/templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>НСУР 2018-2040</title>
    <link rel="stylesheet" href="{% static 'fonts/myriad_pro.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    <link rel="stylesheet" href="{% static 'css/popuo-box.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block css %}{% endblock %}
</head>
<body>
<div class="wrapper">
    <div class="wrapper__inner">
        {% block header %}

        {% endblock %}
        <div id="content">
            {% block slider %}
                {% endblock %}
            <div class="grid row container">
                <div class="sidebar-left col-md-3">
                    {% block sidebar %} {% endblock %}
                </div>
                <div class="main-block col-md-9">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>

        {% block footer %}

        {% endblock %}
    </div>
</div>

<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/core.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block js %}{% endblock %}
<script>
    $('.carousel').carousel();
</script>
</body>
</html>

NSUR/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    {% include 'headers/main.html' %}
{% endblock %}
{% block slider %}
    <div class="slider-block">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="{% static 'uploads/slider-img-1.jpg' %}" alt="slider image">
                    <div class="carousel-caption">
                        <h2>Национальная стратегия Устойчивого Развития 2018-2040</h2>
                        <a class="slider_more-btn" href="#">Подробнее...</a>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static 'uploads/slider-img-1.jpg' %}" alt="slider image">
                    <div class="carousel-caption">
                        <h2>Национальная стратегия Устойчивого Развития 2018-2040</h2>
                        <a class="slider_more-btn" href="#">Подробнее...</a>
                    </div>
                </div>
                <div class="item">
                    <img src="{% static 'uploads/slider-img-1.jpg' %}" alt="slider image">
                    <div class="carousel-caption">
                        <h2>Национальная стратегия Устойчивого Развития 2018-2040</h2>
                        <a class="slider_more-btn" href="#">Подробнее...</a>
                    </div>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="slider-arrow arrow-prev" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="slider-arrow arrow-next" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
{% endblock %}

<!--...-->
{% block sidebar %}
    {% include 'sidebar/main.html' %}
{% endblock %}



{% block content %}
    <div id="news-block">
        <div class="main-news_card">
            {% for post in first %}
                {% if post.video %}
                <div class="news_card_img--wrap">
                    <img class="img-rounded img-responsive" src="{{ post.previewImage.url }}"
                         width="984"
                         height="503" alt="Preview image">
                    <a class="play-icon popup-with-zoom-anim" href="#small-dialog-{{ post.id }}">
                        <span></span>
                    </a>
                    <div id="small-dialog-{{ post.id }}" class="mfp-hide">
                        <iframe src="http://127.0.0.1:8007/media/{{ post.video }}" width="500" height="281" frameborder="0"
                            webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                    </div>
                </div>
                {% else %}
                    <div class="news_card_img--wrap">
                        <img class="img-rounded img-responsive" src="{{ post.pic.url }}"
                             width="984"
                             height="503" alt="Preview image">
                    </div>
                {% endif %}
                <a href="{% url 'news:details' pk=post.pk  %}">
                    <div class="main-news_card_caption card_caption">
                        <h3 class="main-news_card_caption_title card_caption_title">
                            {{ post.title|truncatechars:90 }}</h3>
                        <div class="main-news_card_caption_desc card_caption_desc">
                            {{ post.text|safe|truncatechars:306 }}
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>

        <div class="news_card_list--horizontal">
            {% for post in middle %}
                <div class="news_card_list_item clearfix">
                    {% if post.video %}
                        <div class="news_card_img--wrap pull-left">
                            <img class="img-rounded img-responsive"
                                 src="{{ post.previewImage.url }}" width="312" height="197"
                                 alt="news image">
                            <a class="play-icon popup-with-zoom-anim" href="#small-dialog-{{ post.id }}">
                                <span></span>
                            </a>
                            <div id="small-dialog-{{ post.id }}" class="mfp-hide">
                                <iframe src="http://127.0.0.1:8007/media/{{ post.video }}" width="500" height="281"
                                        frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                            </div>
                        </div>
                    {% else %}
                        <div class="news_card_img--wrap pull-left">
                            <img class="img-rounded img-responsive" src="{{ post.pic.url }}" width="312" height="197"
                                 alt="news image">
                        </div>
                    {% endif %}
                    <a href="{% url 'news:details' pk=post.pk  %}">
                        <div class="card_caption">
                            <h3 class="card_caption_title">{{ post.title|truncatechars:90 }}</h3>
                            <div class="card_caption_desc">
                                {{ post.text|safe|truncatechars:280 }}
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

        <div class="news_card_list--vertical">
            <div class="row">
                {% for post in last %}
                    <div class="col-md-4 col-sm-4 col-xs-4">
                        <div class="news_card_list_item">
                            {% if post.video %}
                                <div class="news_card_img--wrap">
                                    <img class="img-rounded img-responsive" src="{{ post.previewImage.url }}"
                                         width="312" height="197" alt="news image">
                                    <a class="play-icon popup-with-zoom-anim" href="#small-dialog-{{ post.id }}">
                                        <span></span>
                                    </a>
                                    <div id="small-dialog-{{ post.id }}" class="mfp-hide">
                                        <iframe src="http://127.0.0.1:8007/media/{{ post.video }}" width="500"
                                                height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen
                                                allowfullscreen></iframe>
                                    </div>
                                </div>
                            {% else %}
                                <div class="news_card_img--wrap">
                                    <img class="img-rounded img-responsive" src="{{ post.pic.url }}" width="312"
                                         height="197" alt="news image">
                                </div>
                            {% endif %}
                            <a href="{% url 'news:details' pk=post.pk  %}">
                                <div class="card_caption">
                                    <h3 class="card_caption_title">{{ post.title|truncatechars:40 }}</h3>
                                    <div class="card_caption_desc">
                                        {{ post.text|safe|truncatechars:220 }}
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="news_card_list--big">
            <div class="row">
                {% for post in down %}
                    <div class="col-md-6 col-xs-6">
                        <div class="news_card_list_item">
                            {% if post.video %}
                                <div class="news_card_img--wrap">
                                    <img class="img-rounded img-responsive" src="{{ post.previewImage.url }}" width="480"
                                         height="360" alt="news image">
                                    <a class="play-icon popup-with-zoom-anim" href="#small-dialog-{{ post.id }}">
                                        <span></span>
                                    </a>
                                    <div id="small-dialog-{{ post.id }}" class="small-dailog mfp-hide">
{#                                        <iframe src="http://127.0.0.1:8007/media/{{ post.video }}" width="500"#}
{#                                                height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen#}
{#                                                allowfullscreen></iframe>#}
                                        <video width="500" height="281" controls>
                                            <source src="http://127.0.0.1:8007/media/{{ post.video }}" type="video/mp4">
                                        </video>
                                    </div>
                                </div>
                            {% else %}
                                <div class="news_card_img--wrap">
                                    <img class="img-rounded img-responsive" src="{{ post.pic.url }}" width="480"
                                         height="360" alt="news image">
                                </div>
                            {% endif %}
                            <a href="{% url 'news:details' pk=post.pk  %}">
                                <div class="card_caption">
                                    <h3 class="card_caption_title">{{ post.title|truncatechars:60 }}</h3>
                                    <div class="card_caption_desc">
                                        {{ post.text|safe|truncatechars:190 }}
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="clearfix">
            <div class="pull-right btn-more--wrap">
                <a href="{% url 'news:news' %}">Больше новостей
                    <span class="btn-more--circle">
                        <span class="btn-more_arrow"></span>
                    </span>
                </a>
            </div>
        </div>
    </div>
{% endblock %}
{% block footer %}
    {% include 'footers/main.html' %}
{% endblock %}
{% block js %}
    <script src="{% static 'js/modernizr.custom.46884.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
    <script>
        $(document).ready(function () {
            {#var el = document.querySelector('.card_caption_desc p');#}
            {#el.innerHTML = el.innerHTML.replace(/&nbsp;/g,' ');#}
            
            var captionDesk = $(".card_caption_desc p");
            for (var i = 0; i < captionDesk.length; i++) {
                captionDesk[i].innerHTML = captionDesk[i].innerHTML.replace(/&nbsp;/g,' ');
            }

            var captionTitle = $(".card_caption_title");
            for (var i = 0; i < captionTitle.length; i++) {
                captionTitle[i].innerHTML = captionTitle[i].innerHTML.replace(/&nbsp;/g,' ');
            }
        });
    </script>
{% endblock %}