NSUR/TazaKoom/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('news.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NSUR/news/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from .models import News

app_name = 'news'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.mainPage, name='mainPage'),
    url(r'^about/$', views.AboutUs.as_view(), name='aboutUs'),
    url(r'^rukovodstvo/$', views.Rukovodstvo.as_view(), name='rukovodstvo'),
    url(r'^news/', views.postListView, name='news'),
    url(r'^(?P<pk>\d+)/$', views.postDetailsView, name='details'),
    url(r'^emailus/$', views.emailUs, name='emailUs'),
    url(r'^search/$',views.search,name='search'),
    url(r'^email/',views.emailUsFooter,name='email')


]

NSUR/news/forms.py
from django import forms
from . import models

class Email(forms.Form):
    name = forms.CharField()
    tel = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    sendBack = forms.BooleanField()

    class Meta:
        model = models.EmailUs
        fields = ['name','tel','email','text','sendBack']

class EmailFooter(forms.Form):
    nameFooter = forms.CharField()
    emailFooter = forms.EmailField()
    textFooter = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = models.EmailUs
        fields = ['nameFooter','emailFooter','textFooter']

NSUR/templates/footers/main.html
{% load static %}
<footer id="footer">
    <div class="row container">
        <div class="col-md-3 col-md-offset-2">
            <div class="site-map">
                <h3 class="footer_title">карта сайта</h3>
                <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingOne">
                            <h4 class="panel-title">
                                <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                                   aria-expanded="true" aria-controls="collapseOne">
                                    Стратегия НСУР
                                </a>
                            </h4>
                        </div>
                        <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                             aria-labelledby="headingOne">
                            <div class="panel-body">
                                <ul class="site-map_menu">
                                    <li class="site-map_menu_item"><a href="#">Документы</a></li>
                                    <li class="site-map_menu_item"><a href="#">Статистика</a></li>
                                    <li class="site-map_menu_item"><a href="#">О программе</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingTwo">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
                                   href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    Секретариат нсур
                                </a>
                            </h4>
                        </div>
                        <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel"
                             aria-labelledby="headingTwo">
                            <div class="panel-body">
                                <ul class="site-map_menu">
                                    <li class="site-map_menu_item"><a href="#">Документы</a></li>
                                    <li class="site-map_menu_item"><a href="#">Статистика</a></li>
                                    <li class="site-map_menu_item"><a href="#">О программе</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingThree">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
                                   href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    нсур кр
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel"
                             aria-labelledby="headingThree">
                            <div class="panel-body">
                                <ul class="site-map_menu">
                                    <li class="site-map_menu_item"><a href="#">Документы</a></li>
                                    <li class="site-map_menu_item"><a href="#">Статистика</a></li>
                                    <li class="site-map_menu_item"><a href="#">О программе</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-heading" role="tab" id="headingThree">
                            <h4 class="panel-title">
                                <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion"
                                   href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                    гос программы
                                </a>
                            </h4>
                        </div>
                        <div id="collapseThree" class="panel-collapse collapse" role="tabpanel"
                             aria-labelledby="headingThree">
                            <div class="panel-body">
                                <ul class="site-map_menu">
                                    <li class="site-map_menu_item"><a href="#">Документы</a></li>
                                    <li class="site-map_menu_item"><a href="#">Статистика</a></li>
                                    <li class="site-map_menu_item"><a href="#">О программе</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="social-icon-block">
                <h3 class="footer_title">мы в сети</h3>
                <ul class="social-icon-list">
                    {% for facebook in facebook %}
                        <li><a href="{{ facebook.link}}" class="social-icon-circle social-icon_fb"></a></li>
                    {% endfor %}
                    {% for twitter in twitter %}
                    <li><a href="{{ twitter.link }}" class="social-icon-circle social-icon_tw"></a></li>
                    {% endfor %}
                    {% for vk in vk %}
                    <li><a href="{{ vk.link }}" class="social-icon-circle social-icon_vk"></a></li>
                    {% endfor %}
                    {% for pinterest in pinterest %}
                        <li><a href="{{ pinterest.link }}" class="social-icon-circle social-icon_pt"></a></li>
                    {% endfor %}
                    {% for tumblr in tumblr %}
                        <li><a href="{{ tumblr.link }}" class="social-icon-circle social-icon_tmb"></a></li>
                    {% endfor %}
                    {% for dribble in dribble %}
                        <li><a href="{{ dribble.link }}" class="social-icon-circle social-icon_drb"></a></li>
                    {% endfor %}

                    </ul>
            </div>
        </div>
        <div class="col-md-3">
            <div class="feedback-form--footer">
                <h3 class="footer_title">связаться с нами</h3>
                <form enctype="multipart/form-data" method="POST" >
                    {% csrf_token %}
                    <div class="feedback-form_item--footer">

                        <input name="nameFooter" required type="text" id="id_nameFooter" placeholder="ФИО">

                    </div>
                    <div class="feedback-form_item--footer">

                        <input name="emailFooter" required type="email" id="id_emailFooter" placeholder="Email">

                    </div>
                    <div class="feedback-form_item--footer">
								<textarea name="textFooter" required placeholder="Сообщение" id="id_textFooter" cols="30"
                                          rows="4"></textarea>
                    </div>
                    <div class="feedback-form_item--footer">

                        <button type="submit" class="feedback-form_btn--footer">Отправить</button>

                    </div>
                </form>

            </div>
        </div>
    </div>
</footer>