NSUR/TazaKoom/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('news.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

NSUR/news/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views
from .models import News

app_name = 'news'

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.mainPage, name='mainPage'),
    url(r'^about/$', views.AboutUs.as_view(), name='aboutUs'),
    url(r'^rukovodstvo/$', views.Rukovodstvo.as_view(), name='rukovodstvo'),
    url(r'^news/', views.postListView, name='news'),
    url(r'^(?P<pk>\d+)/$', views.postDetailsView, name='details'),
    url(r'^emailus/$', views.emailUs, name='emailUs'),
    url(r'^search/$',views.search,name='search'),
    url(r'^email/',views.emailUsFooter,name='email')


]

NSUR/news/forms.py
from django import forms
from . import models

class Email(forms.Form):
    name = forms.CharField()
    tel = forms.CharField()
    email = forms.EmailField()
    text = forms.CharField(widget=forms.Textarea)
    sendBack = forms.BooleanField()

    class Meta:
        model = models.EmailUs
        fields = ['name','tel','email','text','sendBack']

class EmailFooter(forms.Form):
    nameFooter = forms.CharField()
    emailFooter = forms.EmailField()
    textFooter = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = models.EmailUs
        fields = ['nameFooter','emailFooter','textFooter']

NSUR/templates/tazakoom/aboutus.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

NSUR/templates/tazakoom/emailUS.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NSUR</title>
    <link rel="stylesheet" href="{% static 'fonts/myriad_pro.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,400i,500,500i,600,700,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    <link rel="stylesheet" href="{% static 'css/popuo-box.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="wrapper">
    <div class="wrapper__inner">
        {% block header %}
            {% include 'headers/main.html' %}
        {% endblock %}
        <div id="content">
            <div class="grid row container">
                <div class="main-block col-md-offset-2 col-md-8 col-md-offset-2">
					<div class="feedback-form">
						<h2 class="feedback-form_title">Напишите нам</h2>
						<form enctype="multipart/form-data" method="POST">
                            {% csrf_token %}
							<div class="feedback-form--wrap">
								<div class="feedback-form_item">
									<label for="id_name">имя фамилия</label>
									<input name="name" required type="text" id="id_name" placeholder="Укажите свое имя и фамилию">
								</div>
								<div class="feedback-form_item">
									<label for="id_email">e-mail</label>
									<input name="email" required type="email" id="id_email" placeholder="Укажите свой email">
								</div>
								<div class="feedback-form_item">
									<label for="id_tel">телефон</label>
									<input name="tel" required type="text" id="id_tel" placeholder="Укажите свой номер телефона">
								</div>
								<div class="feedback-form_item">
									<label for="id_text">сообщение</label>
									<textarea name="text" required placeholder="Напишите сообщение" name="text" id="id_text" cols="30"
											  rows="10"></textarea>
								</div>
								<div class="feedback-form_item clearfix">
									<div class="pull-left">
										<input name="sendBack" id="id_sendBack" type="checkbox">
										<label for="id_sendBack">Отправить копию мне</label>
									</div>
									<div class="pull-right">
										<button type="submit" class="feedback-form_btn">Отправить</button>
									</div>
								</div>
							</div>
						</form>
					</div>
				</div>
            </div>
        </div>

        {% block footer %}
            {% include 'footers/main.html' %}
        {% endblock %}
    </div>
</div>

<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/core.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

NSUR/templates/tazakoom/rukovodstvo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>